# Generated by Django 6.0.1 on 2026-02-12 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('instituicao', models.CharField(max_length=200)),
                ('idade', models.PositiveIntegerField()),
                ('ano_letivo', models.CharField(max_length=50)),
                ('nivel_quiz', models.IntegerField(default=1)),
                ('pontuacao_total_quiz', models.IntegerField(default=0)),
                ('nivel_simulador', models.IntegerField(default=1)),
                ('pontuacao_total_simulador', models.IntegerField(default=0)),
                ('filtro_daltonismo', models.CharField(choices=[('normal', 'Padrão'), ('protanopia', 'Protanopia'), ('deuteranopia', 'Deuteranopia'), ('tritanopia', 'Tritanopia'), ('achromatopsia', 'P&B')], default='normal', max_length=20)),
                ('filtro_contraste', models.CharField(choices=[('normal', 'Padrão'), ('alto-contraste', 'Alto Contraste'), ('contraste-invertido', 'Invertido'), ('modo-escuro', 'Modo Escuro')], default='normal', max_length=20)),
                ('lingua', models.CharField(choices=[('pt', 'Português'), ('en', 'English')], default='pt', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
