# Generated by Django 6.0.1 on 2026-02-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='quizzes_realizados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='simuladores_realizados',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
