# Generated by Django 6.0.1 on 2026-02-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_perfil_quizzes_realizados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='soma_percentagens',
            field=models.FloatField(default=0.0),
        ),
    ]
