# Generated by Django 6.0.1 on 2026-02-12 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizPergunta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pergunta', models.TextField()),
                ('nivel_dificuldade', models.IntegerField()),
                ('lingua', models.CharField(choices=[('pt', 'Português'), ('en', 'English')], default='pt', max_length=20)),
                ('explicacao', models.TextField()),
                ('resposta_correta', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoQuiz',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nivel', models.IntegerField()),
                ('pontuacao', models.IntegerField()),
                ('total_perguntas', models.IntegerField()),
                ('percentagem', models.FloatField()),
                ('data_conclusao', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_quiz', to='users.perfil')),
            ],
            options={
                'unique_together': {('perfil', 'nivel', 'data_conclusao')},
            },
        ),
        migrations.CreateModel(
            name='HistoricoQuiz',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('escolha_utilizador', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('foi_correta', models.BooleanField()),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atividades.quizpergunta')),
                ('resultado_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='atividades.resultadoquiz')),
            ],
        ),
        migrations.CreateModel(
            name='OpcaoPergunta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('letra', models.CharField(max_length=1)),
                ('texto', models.CharField(max_length=255)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='atividades.quizpergunta')),
            ],
            options={
                'unique_together': {('pergunta', 'letra')},
            },
        ),
    ]
